language: python
sudo: true
python:
  - "2.7"

install:
  - sudo apt-get install -y rpm

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.

after_success:
  - echo "Packaging for BinTray - Debian..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
  - echo "Packaging for BinTray - RPM..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm

deploy:
  # PyPi deployment for tagged commits:
  # -> build a PyPi package when a version is set
  # Bintray deployment for develop branch and tagged commits:
  # -> build Deb/Rpm packages on develop branch or when a version is set
  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
    user: alignak
    password:
      secure: "aB2jCErUd8qv5wKS+EgG4zTG/jIvXr/UhUnwbYkKb1G4SIyrVEVlXWNRokDV5A8Xjje0mRnSSnMwyKbHHhig4KfRY/VfsyarRxCg2qT71kpxjS5aFsOBxpKDlxR1u7p4KZVmtjfQbFYLt8cI+mossETfO+GLwcpSy0wqNQZq7HPJf5gMqYzL/24inKvkmdolZBB1neU7AcjuqFb5h+ZPQ+XDTU6FmkqIQP0fPIjHTtxSoRxnL79cJwcbwo5nuYPXOSELqyfoWpbG++FDZQ5Nu/pRp3rPfNcc96J5JZQLITTqFpqLApapV6kUFfO2avyehORvIEiCKSDnXsEd10GjCIBxrfJnEIljHPyyxFeihqeRIVSs3hJhDL2iqbWFnK6dQYDxRMrMA5xGpusYBtZnRC6+/4esTljQo9G5ZgTdQ/VDJmo2cWE/sxhuHikMT5t04CiwFaS4rXhNwDWYSs64cPpQBfyXIyV6V9BHxRL+vcl80uAhg5aVPh+548+6f5pAuNxmpRR7Px7XXknhZHx5v8lsdK/fryXt5+LzXOao4pTecpqfFMov5EaMv4BiCV7xB+Hh9Nkr3s/QKY/E7JtgmwCH5MI0C39pzQKgryjYyGIiSC+iPc66URFtMI8f/BwB+EpYOTnO60Ds2QvsXl3NJe1E/4o/kXzG+YZe4KZexPE="
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      tags: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      tags: true
