language: python
sudo: true
python:
  - "2.7"

install:
  - sudo apt-get install -y rpm

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.

after_success:
  - echo "Packaging for BinTray - Debian..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
  - echo "Packaging for BinTray - RPM..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm

deploy:
  # PyPi deployment for tagged commits:
  # -> build a PyPi package when a version is set
  # Bintray deployment for develop branch and tagged commits:
  # -> build Deb/Rpm packages on develop branch or when a version is set
  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
    user: alignak
    password:
      secure: "Ewuo7difK4Gc/20wYy2/y5WTf1Y1ry0KHx+vtcyd3BGxnZK91/nfFH0C5Z9523XkTv7jAgQKDH8R3f6Epc6jGuHkLor3HmGbQac0wTAc7gKaM5AlmtyW1iBo4HqbOSM7l36AQyqMGTifw7w2xPbosq1Y4lozadrOC1X+p8xS8re3LNohg9SMqPhRu6ChIOfA+/DvfsEAFFqLjlvg+g+klCDmr0PqgUwCHBLh0Uz+xochFWqT6BRckIYeZeWlErzr+zqAUai8/+V3SsQ4u/tPgoVmie1sBkVzaxbXOEttPYO4VtywjTuiFdQUiwqk/S6vOWzJOoV9n52uHUF2ni3aXURgMXE+pDljU4r77ieVzimOOuWNODlLAUcXG7RlmSrKVRjS1Yt55TQfSxDLwMhSFf88Z7ucG08mzdfSKPxzogqZO9E9s9abOa0wbEI2JwYJbFjhKD61EjRSGsbFEIu1i0A9BLGFXr72iXrEZLbam9jhnV09cp6AmVvgK4IF+JU3e72dGh4kQ2MsYzqx+AQRlqvSMAqKiv4TGbinfC0/W7nDQLoCMvS7lhTBW4ULaNHggePcMGEhkw70WPySB0i1zhrlT06kPw333N5PXvLOd0F+OJbh2XhvscwtvpNc/AJdKaJMWDZxPN3RXN9GSZNcrygMMumotcx++s0tyx4hmtg="
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      tags: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "swuJTaoToIIoN73pXgOupNNYrLyNh7CtoINyCD+NJRGUZS3A82OaLsA8oCpnk913p/xkYIylknRwtX12i3VYzVXv9FD3+TxAyiEhxV6kPry7nDCqPxTSVncKih/TD5SCSg+crRASu1Q1NSeJJrv9BsbAeoJiyuF5eapm4pdsXPTadOLWodE+/w1wMIyuRNLcr2oxLbMjCPvIcd4HPh8UIlxNxuFsc0IgPrFGww3/yIM+BKZ/mxB2qV9WYBwglHZKRZBkK1AolgAx4Y66lhj5IdvKVxza457xHXGA8sA2vE3wHzCIAgVbv6RykdrLz76+XK0FB69a+Os8JXNavzj6V7kp6REs34fMDtXBBtM1j924Z4l8LzprtbIBCTNdHXXeGXjzYamyLn/J/NPzyzV33rWR9alhz+2XMtkvesLfyLQrnUnlrndaB9OhRBpiYgFHsnAPhWrGBkZ6nLzkeZvjEykffcVP/DNb0GRGNhg2SEIjfyXb/Zvc/kLa4UnMuw+VsU5xptC9xV9vB8o3NgJPzUNcrXrsWz9rTmE3XGGzB0/kZKxtP3ptl+SbAcz0jLPmfM2muUE6LLFon7WEOs6I0iPe2+21qXkaGmbGM6iZYZole0J2qdQJdO6WCiMJcl8gTRfloaW97INF53Q2ADHzGvwiECTpVckGQqD2RIXrFWQ="
    on:
      tags: true
